package com.chat.common;

public enum MessageType {
    LOGIN,
    LOGOUT,
    CHAT_ALL,
    CHAT_PRIVATE,
    UPDATE_USERS,
    FILE,
    IMAGE,
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    ADD_FRIEND_REQUEST,
    ADD_FRIEND_RESPONSE,
    FRIEND_LIST,
    AVATAR_UPDATE,
    ADMIN_GET_USERS,
    ADMIN_USER_LIST,
    ADMIN_BAN_USER,
    ADMIN_UNBAN_USER,
    ADMIN_DELETE_USER,
    FORCE_LOGOUT
}
